MBI/main/routes.py
from flask import render_template, request, Blueprint, flash, redirect, url_for, current_app, abort, send_file, jsonify
from flask_login import login_user, current_user, logout_user, login_required
from MBI.models import texto, User, fondo, datos_fondo, documento, tipos_archivo, noticia, contacto, formulario, webinar, speaker_webinar, clientes_webinar, usuarios_webinar, preguntas
from MBI.forms import formtexto, formLogin, formFP, formAccount, formArchivo, formAccountCorredora, formNoticia, formLegalesAGF, formContacto, formFondo, formDocFondo, formLoginWebinar, formWebinar, formSpeaker, formLoginWebinar2, formPreguntaWebinar
from MBI.funciones import enviar_mail, enviar_pregunta
from MBI import db, bcrypt, mail, socketio
import os, datetime, pyodbc, json, pyexcel, time
from datetime import timedelta
from flask_mail import Message
from flask_socketio import join_room, leave_room, send
main = Blueprint('main', __name__)

#chat
@socketio.on('incoming-msg')
def on_message(data):
    """Broadcast messages"""

    msg = data["msg"]
    username = data["username"]
    room = data["room"]

    ip_access = request.access_route[0]
    fecha = datetime.date.today()
    user = usuarios_webinar.query.filter_by(ip=ip_access).order_by(usuarios_webinar.fecha_ultimo_login.desc()).first()
    web = webinar.query.filter_by(link_page=room).first()
    preg = preguntas(pregunta=msg, fecha_pregunta=fecha, usuario=user.rut, webinar=web.id)
    db.session.add(preg)
    db.session.commit()
    # Set timestamp
    time_stamp = time.strftime('%b-%d %I:%M%p', time.localtime())
    send({"username": username, "msg": msg, "time_stamp": time_stamp}, room=room)
    msj = '<p>'+msg+'</p><br><p>Pregunta enviada por: '+user.nombre+' - '+user.correo+'</p>'
    enviar_pregunta('Pregunta Webinar de '+str(user.nombre),msj,web)


@socketio.on('join')
def on_join(data):
    """User joins a room"""

    username = data["username"]
    room = data["room"]
    join_room(room)

    # Broadcast that new user has joined
    send({"msg": username + " ha entrado al webinar"}, room=room)


@socketio.on('leave')
def on_leave(data):
    """User leaves a room"""

    username = data['username']
    room = data['room']
    leave_room(room)
    send({"msg": username + " ha dejado el webinar"}, room=room)

#-----------------------------------
@main.route("/layout")
def layout():
    return render_template('layout.html', title='layout')

@main.route("/test")
def test():
    webi = webinar.query.filter_by(id=31).first()
    ip = request.access_route[0]
    preg = formPreguntaWebinar()
    user = usuarios_webinar.query.filter_by(ip=ip).order_by(usuarios_webinar.fecha_ultimo_login.desc()).first()
    name = user.nombre#+' - '+user.correo
    return render_template('prueba.html', video= '', chat=webi.chat, speakers =[], mod = [], webi = webi, form = preg, rooms=webi.link_page, username = name)

@main.route("/webinar/<id_webinar>/chat")
def chat_webinar(id_webinar):
    webi = webinar.query.filter_by(id=id_webinar).first()
    return render_template('Admin/admin-chat-webinar.html', rooms=webi.link_page)

def leer_archivo(archivo):
    filename = archivo.filename
    extension = filename.split(".")[-1]
    content = archivo.read()
    sheet = pyexcel.get_array(file_type=extension, file_content=content, delimiter=';')
    del sheet[0]
    aux = {}
    for s in sheet:
        #aux = {}
        rut = str(s[0]).strip()
        rut = rut.replace('.', '')
        rut = rut.replace('-', '')
        rut = rut.lower()
        correo = s[1]
        aux[rut]={"correo": correo, "ip": '', "asistencia":''}
    return aux

@main.route("/api/pregunta/", methods=['POST'])
def pregunta():
    if request.method == 'POST':
        data = request.get_json()
        webi = data['webinar']
        tipo = data['tipo']
        msj = data['mensaje']
        ip_access = request.access_route[0]
        fecha = datetime.date.today()
        user = usuarios_webinar.query.filter_by(ip=ip_access, fecha_ultimo_login=fecha).first()
        web = webinar.query.filter_by(link_page=webi, privado=tipo).first()
        preg = preguntas(pregunta=msj, fecha_pregunta=fecha, usuario=user.rut, webinar=web.id)
        db.session.add(preg)
        db.session.commit()
        msj = '<p>'+msj+'</p><br><p>Pregunta enviada por: '+user.nombre+' - '+user.correo+'</p>'
        enviar_pregunta('Pregunta Webinar de '+str(user.nombre),msj,web)
        return jsonify({"status":"OK"}),200
    return jsonify({"status":"ERROR"}),400

@main.route("/admin/webinar/<id_webinar>/preguntas")
def ver_preguntas(id_webinar):
    pregs = preguntas.query.filter_by(webinar=id_webinar)
    pregunta = []
    for p in pregs:
        aux ={}
        aux['fecha'] = p.fecha_pregunta
        aux['pregunta'] = p.pregunta
        user = usuarios_webinar.query.filter_by(rut=p.usuario).first()
        aux['nombre'] = user.nombre
        aux['correo'] = user.correo
        pregunta.append(aux)
    return render_template('Admin/admin-ver-preguntas.html', data = pregunta, webinar = id_webinar)


@main.route("/webinar/<tipo>/<id_webinar>", methods=['GET', 'POST'])
def webinar_view(tipo, id_webinar):
    tip = int(tipo)
    webi = webinar.query.filter_by(link_page=id_webinar, privado=tip).first()
    ip = request.access_route[0]
    fecha = datetime.datetime.now() + timedelta(hours=1)
    if webi:
        print(fecha, webi.fecha)
        if fecha < webi.fecha:
            mensaje = 'El webinar aún no esta disponible, por favor ingresa nuevamente en la fecha y hora que corresponde.'
            return render_template('errores/error-webinar.html', title='Login', error = mensaje, error2='', tipo = 0)
        else:
            if tipo == '1' or tipo == 1:
                webi = webinar.query.filter_by(link_page=id_webinar, privado=1).first()
                if webi == None:
                    mensaje = 'Webinar no encontrado, revise la URL dada.'
                    return render_template('errores/error-webinar.html', title='Login', error = mensaje, error2='', tipo=0)
                else:
                    cli_webi = clientes_webinar.query.filter_by(webinar= webi.id).first()
                    mod = speaker_webinar.query.filter_by(webinar=webi.id, tipo = 1).first()
                    spk = speaker_webinar.query.filter_by(webinar=webi.id, tipo = 2)
                    aux = webi.link_youtube
                    if '=' in aux:
                        yt_video = aux.split('=')[-1]
                    else:
                        yt_video = aux.split('/')[-1]
                    if cli_webi != None:
                        ips = cli_webi.ip_cliente
                        ips = ips.split('-')
                        if ip in ips:
                            preg = formPreguntaWebinar()
                            user = usuarios_webinar.query.filter_by(ip=ip).order_by(usuarios_webinar.fecha_ultimo_login.desc()).first()
                            name = user.nombre#+' - '+user.correo
                            return render_template('webinar.html', video= yt_video, chat=webi.chat, speakers =spk, mod = mod, webi = webi, form = preg, rooms=webi.link_page, username = name)
                        else:
                            return redirect(url_for('.login_webinar',webinar_id=webi.link_page))
                    else:
                        mensaje = 'Existen inconvenientes con la URL dada.'
                        return render_template('errores/error-webinar.html', title='Login', error = mensaje, error2='', tipo=0)
            elif tipo == '0' or tipo == 0:
                webi = webinar.query.filter_by(link_page=id_webinar, privado=0).first()
                if webi == None:
                    mensaje = 'Webinar no encontrado, revise la URL dada.'
                    return render_template('errores/error-webinar.html', title='Login', error = mensaje, error2='', tipo=0)
                else:
                    cli_webi = clientes_webinar.query.filter_by(webinar= webi.id).first()
                    mod = speaker_webinar.query.filter_by(webinar=webi.id, tipo = 1).first()
                    spk = speaker_webinar.query.filter_by(webinar=webi.id, tipo = 2)
                    aux = webi.link_youtube
                    if '=' in aux:
                        yt_video = aux.split('=')[-1]
                    else:
                        yt_video = aux.split('/')[-1]
                    if cli_webi != None:
                        ips = cli_webi.ip_cliente
                        ips = ips.split('-')
                        if ip in ips:
                            preg = formPreguntaWebinar()
                            user = usuarios_webinar.query.filter_by(ip=ip).order_by(usuarios_webinar.fecha_ultimo_login.desc()).first()
                            name = user.nombre#+' - '+user.correo
                            return render_template('webinar.html', video= yt_video, chat=webi.chat, speakers =spk, mod = mod, webi = webi, form = preg, rooms=webi.link_page, username =name)
                        else:
                            return redirect(url_for('.login_webinar',webinar_id=webi.link_page))
                    else:
                        return redirect(url_for('.login_webinar',webinar_id=webi.link_page))
    else:
        mensaje = 'Url de webinar incorrecta.'
        return render_template('errores/error-webinar.html', title='Login', error = mensaje, error2='', tipo = 0)

@main.route("/webinar/login/<webinar_id>", methods=['GET', 'POST'])
def login_webinar(webinar_id):
    
    webi = webinar.query.filter_by(link_page=webinar_id).first()
    clients = clientes_webinar.query.filter_by(webinar=webi.id).first()
    ip_access = request.access_route[0]
    if webi:
        if clients:
            if ip_access in clients.ip_cliente:
                if webi.privado:
                    return redirect(url_for('.webinar_view', id_webinar = webi.link_page, tipo=1))
                else:

MBI/templates/errores/error-webinar.html
{% extends "layout.html" %}
    {% block import %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/accordion.css') }}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    {% endblock import %}
    {% block menu2 %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/asset-management"><img src="{{ url_for('static', filename='img/head1.svg') }}" alt="icono"></a>
                <a class="nav-link" href="/asset-management">Asset Mangement</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/wealth-management"><img src="{{ url_for('static', filename='img/head2.svg') }}" alt="icono"></a>
                <a class="nav-link" href="/wealth-management">Wealth Management</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/corredores"><img src="{{ url_for('static', filename='img/head3.svg') }}" alt="icono"></a>
                <a class="nav-link" href="/corredores">Corredores de Bolsa</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/activos-alternativos"><img src="{{ url_for('static', filename='img/head4.svg') }}" alt="icono"></a>
                <a class="nav-link" href="/activos-alternativos">Activos Alternativos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/quienes-somos"><img src="{{ url_for('static', filename='img/head5.svg') }}" alt="icono"></a>
                <a class="nav-link" href="/quienes-somos">Quienes Sómos</a>
            </li>
        </ul>
    {% endblock menu2 %}
    {% block contenido %}
        <div class="nuestros">
            <div class="container">
                <div class="row error">
                    {% if tipo == 0 %}
                        <div>
                            <p class="error-es">{{error}}</p>
                        </div>
                        <div class="flex-error">
                            <a class="btn-ir-servicios" href="{{ url_for('main.home') }}">Volver al Inicio</a>
                        </div>
                    {% else %}
                        <div>
                            <p class="error-es">{{error}}</p>
                        </div>
                        <div>
                            <p class="error-en">{{error2}}</p>
                        </div>
                        <div class="flex-error">
                            <a class="btn-ir-servicios" href="{{ url_for('main.login_webinar', webinar_id=tipo) }}">Volver a Login de Webinar</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endblock contenido %}
    {% block Jquery %}
        <script src="{{ url_for('static', filename='js/jquery-3.4.0.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
    {% endblock Jquery%}

MBI/templates/errores/error.html
{% extends "layout.html" %}
    {% block import %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/accordion.css') }}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    {% endblock import %}
    {% block menu2 %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/asset-management"><img src="{{ url_for('static', filename='img/head1.svg') }}" alt="icono"></a>
                <a class="nav-link" href="/asset-management">Asset Mangement</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/wealth-management"><img src="{{ url_for('static', filename='img/head2.svg') }}" alt="icono"></a>
                <a class="nav-link" href="/wealth-management">Wealth Management</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/corredores"><img src="{{ url_for('static', filename='img/head3.svg') }}" alt="icono"></a>
                <a class="nav-link" href="/corredores">Corredores de Bolsa</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/activos-alternativos"><img src="{{ url_for('static', filename='img/head4.svg') }}" alt="icono"></a>
                <a class="nav-link" href="/activos-alternativos">Activos Alternativos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/quienes-somos"><img src="{{ url_for('static', filename='img/head5.svg') }}" alt="icono"></a>
                <a class="nav-link" href="/quienes-somos">Quienes Sómos</a>
            </li>
        </ul>
    {% endblock menu2 %}
    {% block contenido %}
        <div class="nuestros">
            <div class="container">
                <div class="row error">
                    <div>
                        <p class="error-es">Al parecer estamos experimentando dificultades técnicas, por favor intenta más tarde.</p>
                    </div>
                    <div>
                        <p class="error-en">Apparently we are experiencing technical difficulties, please try again later.</p>
                    </div>
                    <div class="flex-error">
                        <a class="btn-ir-servicios" href="{{ url_for('main.home') }}">Volver al Inicio</a>
                    </div>
                    <div style="display: none;">{{er}}</div>
                </div>
            </div>
        </div>
    {% endblock contenido %}
    {% block Jquery %}
        <script src="{{ url_for('static', filename='js/jquery-3.4.0.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
    {% endblock Jquery%}